const express = require('express')
const app = express()
const port = 3001;
const axios = require('axios');
const _ = require('lodash')
const moment = require('moment');
const async = require("async");

app.get('/getData', (req, res) => {

  const {symbol} = req.query

  const config = {
    method: 'get',
    url: `https://query2.finance.yahoo.com/v8/finance/chart/${symbol}?region=US&lang=en-US&includePrePost=false&interval=1m&useYfid=true&range=1d&corsDomain=finance.yahoo.com&.tsrc=finance`,
    headers: {
      'authority': 'query1.finance.yahoo.com',
      'sec-ch-ua': '"Google Chrome";v="95", "Chromium";v="95", ";Not A Brand";v="99"',
      'sec-ch-ua-mobile': '?1',
      'user-agent': 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Mobile Safari/537.36',
      'sec-ch-ua-platform': '"Android"',
      'accept': '*/*',
      'origin': 'https://finance.yahoo.com',
      'sec-fetch-site': 'same-site',
      'sec-fetch-mode': 'cors',
      'sec-fetch-dest': 'empty',
      'accept-language': 'en-US,en;q=0.9',
      'proxy': 'https://finance.yahoo.com/',
      'Cookie': 'B=6ll3g51gpjeru&b=3&s=qo'
    }
  };

  axios(config)
      .then(function (response) {
        res.send(response.data)
      })
      .catch(function (error) {
        res.send(error)
      });
})


app.get('/earnings', (req,res) =>{
  //console.log(req.query.date)
  const {date} = req.query;
  var config = {
    method: 'get',
    url: `https://api.nasdaq.com/api/calendar/earnings?date=${date}`,
    headers: {
      'authority': 'api.nasdaq.com',
      'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"',
      'accept': 'application/json, text/plain, */*',
      'sec-ch-ua-mobile': '?1',
      'user-agent': 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Mobile Safari/537.36',
      'sec-ch-ua-platform': '"Android"',
      'origin': 'https://www.nasdaq.com',
      'sec-fetch-site': 'same-site',
      'sec-fetch-mode': 'cors',
      'sec-fetch-dest': 'empty',
      'referer': 'https://www.nasdaq.com/',
      'accept-language': 'en-US,en;q=0.9'
    }
  };

  axios(config)
      .then(function (response) {
        res.send(response.data)
      })
      .catch(function (error) {
        res.send(error)
      });
})

app.get('/news', (req,res) =>{

  const {symbol} = req.query

  var config = {
    method: 'get',
    url: `https://ycharts.com/news/articles?num=30&securityId=${symbol}&useCountryCodeFilter=false`,
    headers: {
      'authority': 'ycharts.com',
      'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"',
      'accept': 'application/json, text/plain, */*',
      'x-requested-with': 'XMLHttpRequest',
      'sec-ch-ua-mobile': '?1',
      'user-agent': 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Mobile Safari/537.36',
      'sec-ch-ua-platform': '"Android"',
      'sec-fetch-site': 'same-origin',
      'sec-fetch-mode': 'cors',
      'sec-fetch-dest': 'empty',
      'referer': 'https://ycharts.com/companies/AMZN',
      'accept-language': 'en-US,en;q=0.9',
      'cookie': 'ycsessionid=nj5gbstqbz34z4sr7zed5dhzkhi3z81b; _ga=GA1.2.1999833280.1639275468; _gid=GA1.2.1971042957.1639275468; __gads=ID=26c16c421502d515:T=1639275468:S=ALNI_MYQT8yMxvf5QoJnmh2D-_049ibAIQ; __hstc=69688216.d791d385ce1fc8e7d91421980dbc95aa.1639275470496.1639275470496.1639275470496.1; hubspotutk=d791d385ce1fc8e7d91421980dbc95aa; __hssrc=1; _gcl_au=1.1.777972877.1639275471; _fbp=fb.1.1639275470999.695507323; messagesUtk=2137a056052844bc82dea8c9d53c9dd8; __hssc=69688216.3.1639275470497; page_view_ctr=4; ycsessionid=nj5gbstqbz34z4sr7zed5dhzkhi3z81b'
    }
  };

  axios(config)
      .then(function (response) {
        res.send(response.data)
      })
      .catch(function (error) {
        res.send(error)
      });

})

app.get('/getUS', (req,res) =>{

  var config = {
    method: 'get',
    url: 'https://www.marketwatch.com/api/marketoverview/type/US',
    headers: {
      'authority': 'www.marketwatch.com',
      'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"',
      'tracestate': '1022681@nr=0-1-1684273-753720625-4f6f1ac2e07aff00----1639623480489',
      'traceparent': '00-7dca6630a70084821501f0ef5d014260-4f6f1ac2e07aff00-01',
      'sec-ch-ua-mobile': '?0',
      'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36',
      'newrelic': 'eyJ2IjpbMCwxXSwiZCI6eyJ0eSI6IkJyb3dzZXIiLCJhYyI6IjE2ODQyNzMiLCJhcCI6Ijc1MzcyMDYyNSIsImlkIjoiNGY2ZjFhYzJlMDdhZmYwMCIsInRyIjoiN2RjYTY2MzBhNzAwODQ4MjE1MDFmMGVmNWQwMTQyNjAiLCJ0aSI6MTYzOTYyMzQ4MDQ4OSwidGsiOiIxMDIyNjgxIn19',
      'accept': 'application/html',
      'sec-ch-ua-platform': '"macOS"',
      'sec-fetch-site': 'same-origin',
      'sec-fetch-mode': 'cors',
      'sec-fetch-dest': 'empty',
      'referer': 'https://www.marketwatch.com/investing/stock/AMZN',
      'accept-language': 'en-US,en;q=0.9',
      'cookie': 'kayla=g=3b0063e2e4744829acb5bc8c15853e2f; gdprApplies=false; ab_uuid=181e360f-1da3-42ea-8113-3b16f3f2d61a; CBSMWQuoteSeen=1; _pnvl=false; pushly.user_puuid=VFENj7H9txC2MfYvEjfbr2wmCVuTGzn0; _pndnt=; letsGetMikey=enabled; _ncg_id_=4c75aefb-1295-4cea-a53f-74dd817c5f6a; _sp_v1_uid=1:845:60a847df-8aec-4f26-b9c8-428365a16600; _sp_v1_ss=1:H4sIAAAAAAAAAItWqo5RKimOUbLKK83J0YlRSkVil4AlqmtrlXSoqiwWACMYp9h2AAAA; _sp_v1_opt=1:; _sp_v1_csv=null; _sp_v1_lt=1:; consentUUID=16183ddf-c4c5-4e2e-b543-b777ce557ee0; AMCVS_CB68E4BA55144CAA0A4C98A5%40AdobeOrg=1; _rdt_uuid=1638854778645.cd518e8d-0cf6-402d-8170-a11e4b719b6b; _ncg_g_id_=a261eccd-3685-41cb-afd7-3a281b10a669; _gcl_au=1.1.1610030327.1638854779; cX_P=kwvntkdt8x3kj7h5; usr_bkt=rGgki1wrhs; cX_S=kwvntkdzitm6lc26; _fbp=fb.1.1638854778807.1721938035; __gads=ID=bdf9ea9a1d3457d8:T=1638854778:S=ALNI_MY9LJjuuyrnyJkQvk7JYS1KiwyhBQ; s_cc=true; cX_G=cx%3A2qmv6vxnwbi432fqk3lzpakcpp%3A3amev8livnjn2; kuid=v1z2ci5ic; _pnlspid=11018; recentqsmkii=Stock-US-AMZN; permutive-id=9da6b9df-2f7f-454b-b324-a13295ad6348; mw_loc=%7b%22Country%22%3a%22US%22%2c%22Region%22%3a%22AR%22%2c%22City%22%3a%22BENTONVILLE%22%2c%22Continent%22%3a%22NA%22%2c%22County%22%3a%5b%22BENTON%22%5d%7d; _ncg_sp_ses.f57d=*; AMCV_CB68E4BA55144CAA0A4C98A5%40AdobeOrg=1585540135%7CMCIDTS%7C18978%7CMCMID%7C63837260424387838350943148174020185448%7CMCAAMLH-1640226405%7C9%7CMCAAMB-1640226405%7CRKhpRz8krg2tLO6pguXWp5olkAcUniQYPHaMWWgdJ3xzPWQmdj0y%7CMCOPTOUT-1639628805s%7CNONE%7CMCAID%7CNONE%7CvVersion%7C4.4.0; _parsely_session={%22sid%22:3%2C%22surl%22:%22https://www.marketwatch.com/tools/quotes/lookup.asp%22%2C%22sref%22:%22https://www.google.com/%22%2C%22sts%22:1639621605810%2C%22slts%22:1639194265114}; _parsely_visitor={%22id%22:%22pid=aebd421e3cf43f1ed5e41cc28d828a3c%22%2C%22session_count%22:3%2C%22last_session_ts%22:1639621605810}; fullcss-quote=quote-b112386e71.min.css; icons-loaded=true; ksg=u078fu8l7,vlpkh3fty,t9f4zevbn,vow5tmibz,uhhxj8as8,t963r1c9g,vow7nrapf,uaac1ephd,uaachbgmo,vpud310cy,t9998rd02,uaouthrkv,u00fyqzbu,ug4pdktsx,ub7cvsdvn,t98rq0q4o,uaos8yyz5,uicrvbqb7,vmurdl1tf,u6mi3tzwa; _pnss=blocked; permutive-session=%7B%22session_id%22%3A%22be7d0614-ea51-4040-97df-0b3e410afb97%22%2C%22last_updated%22%3A%222021-12-16T02%3A54%3A32.890Z%22%7D; cto_bundle=F0KPB196amllT0NucG4lMkYlMkJZelBQNG04OXNZc2VaOVBmRDRQOUo4UjdRSGxrVkVXUERsdmxUQmw1MW00VWhpRldKNTJjMTgxTlklMkZiWHNPbnpwUGxMVjRGSk1WR2kxTmd6Y3pNUmRXUzNpWnhKUEVYenBuTE43cVlLQmllY1VsaiUyRlpPNVl3a2RUVlRSWko5SHlZSUtZMEhBU0dKRzQ3NlVCdSUyQk5jT0tjQUsxbjRrMjZyTTZvMGRCVUFxM2FlQ1cwdVdQMSUyQmtMWGJTcHl6R05YV2xlT0JLY0hpMzVRJTNEJTNE; utag_main=v_id:017d935b5c6e004408e55584287805078001c07000942$_sn:3$_ss:0$_st:1639625269501$vapi_domain:marketwatch.com$ses_id:1639621605038%3Bexp-session$_pn:4%3Bexp-session$_prevpage:MW_Quote_Page%3Bexp-1639627069506; _ncg_sp_id.f57d=4c75aefb-1295-4cea-a53f-74dd817c5f6a.1638854778.3.1639623470.1639194454.d3b38d39-3953-4e9e-8578-0b45e0318bc1; _sp_v1_data=2:371411:1638854778:0:10:0:10:0:0:_:-1; cX_T=kx8dhangp5sqootw; s_tp=4614; s_ppv=MW_Quote_Page%2C17%2C17%2C789; s_sq=djglobal%3D%2526c.%2526a.%2526activitymap.%2526page%253DMW_Quote_Page%2526link%253DEurope%2526region%253DBODY%2526pageIDType%253D1%2526.activitymap%2526.a%2526.c%2526pid%253DMW_Quote_Page%2526pidt%253D1%2526oid%253Dhttps%25253A%25252F%25252Fwww.marketwatch.com%25252Fmarkets%25252Feurope-middle-east%2526ot%253DA; gdprApplies=false'
    }
  };

  axios(config)
      .then(function (response) {
        //console.log(JSON.stringify(response.data));
        res.send(response.data)
      })
      .catch(function (error) {
        //console.log(error);
        res.send(error)
      });



})

app.get('/getStockDetails', (req,res) =>{

  const {symbol} = req.query

  var config = {
    method: 'get',
    url: `https://www.wsj.com/market-data/quotes/${symbol}?id=%7B%22ticker%22%3A%22${symbol}%22%2C%22countryCode%22%3A%22US%22%2C%22exchange%22%3A%22%22%2C%22type%22%3A%22STOCK%22%2C%22path%22%3A%22%2F${symbol}%22%7D&type=quotes_chart`,
    headers: {
      'authority': 'www.wsj.com',
      'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"',
      'sec-ch-ua-mobile': '?0',
      'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36',
      'sec-ch-ua-platform': '"macOS"',
      'accept': '*/*',
      'sec-fetch-site': 'same-origin',
      'sec-fetch-mode': 'cors',
      'sec-fetch-dest': 'empty',
      'referer': `https://www.wsj.com/market-data/quotes/${symbol}`,
      'accept-language': 'en-US,en;q=0.9',
      'cookie': 'DJSESSION=country%3Dus%7C%7Ccontinent%3Dna%7C%7Cregion%3Dks%7C%7Ccity%3Dstilwell%7C%7Clatitude%3D38.7858%7C%7Clongitude%3D-94.6907%7C%7Ctimezone%3Dcst%7C%7Czip%3D66085; wsjregion=na%2Cus; gdprApplies=false; ccpaApplies=false; usr_prof_v2=eyJpYyI6MH0%3D; ab_uuid=9fa1d722-c96d-4f73-9317-87618b79f240; usr_bkt=q85AaJVP78; cX_P=kxc34r6c7qy9zc4x; cX_S=kxc34r6gt57ffb44; wsjregion=na%2Cus; gdprApplies=false; ccpaApplies=false; usr_prof_v2=eyJpYyI6MX0%3D'
    }
  };

  axios(config)
      .then(function (response) {
        //console.log(JSON.stringify(response.data));
        res.send(response.data)
      })
      .catch(function (error) {
        //console.log(error);
        res.send(error)
      });




})

app.get('/getStockHistory', (req,res) =>{

  const {symbol} = req.query

  var config = {
    method: 'get',
    url: 'https://api-secure.wsj.net/api/michelangelo/timeseries/history?json=%7B%22Step%22%3A%22P1D%22%2C%22TimeFrame%22%3A%22P29D%22%2C%22EntitlementToken%22%3A%2257494d5ed7ad44af85bc59a51dd87c90%22%2C%22IncludeMockTick%22%3Atrue%2C%22FilterNullSlots%22%3Afalse%2C%22FilterClosedPoints%22%3Atrue%2C%22IncludeClosedSlots%22%3Afalse%2C%22IncludeOfficialClose%22%3Atrue%2C%22InjectOpen%22%3Afalse%2C%22ShowPreMarket%22%3Afalse%2C%22ShowAfterHours%22%3Afalse%2C%22UseExtendedTimeFrame%22%3Atrue%2C%22WantPriorClose%22%3Atrue%2C%22IncludeCurrentQuotes%22%3Afalse%2C%22ResetTodaysAfterHoursPercentChange%22%3Afalse%2C%22Series%22%3A%5B%7B%22Key%22%3A%22STOCK%2FUS%2FXNAS%2FAMZN%22%2C%22Dialect%22%3A%22Charting%22%2C%22Kind%22%3A%22Ticker%22%2C%22SeriesId%22%3A%22s1%22%2C%22DataTypes%22%3A%5B%22Last%22%5D%7D%5D%7D&ckey=57494d5ed7',
    headers: {
      'Connection': 'keep-alive',
      'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"',
      'Accept': 'application/json, text/javascript, */*; q=0.01',
      'Dylan2010.EntitlementToken': '57494d5ed7ad44af85bc59a51dd87c90',
      'sec-ch-ua-mobile': '?0',
      'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36',
      'sec-ch-ua-platform': '"macOS"',
      'Origin': 'https://www.wsj.com',
      'Sec-Fetch-Site': 'cross-site',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Dest': 'empty',
      'Referer': 'https://www.wsj.com/',
      'Accept-Language': 'en-US,en;q=0.9'
    }
  };

  axios(config)
      .then(function (response) {
        //console.log(JSON.stringify(response.data));
        res.send(response.data)
      })
      .catch(function (error) {
        //console.log(error);
        res.send(error)
      });
})

app.get('/getHotList', (req,res) =>{

  const {symbol} = req.query

  const url = 'https://ql.stocktwits.com/batch?symbols=TSLA,SPY,AMZN,AAPL,QQQ,NVDA,AMT,GOOGL,BABA,GOOG,MRNA,AMD,IWM,MSFT,FB,PFE,TQQQ,SHOP,PYPL,BA,ROKU,SQ,VXX,F,NFLX,ADBE,MU,AMC,CERN,RBLX,COIN,EEM,LCID,DIS,UPST,GM,CCL,ZM,NVAX,TSM,BAC,NIO,BKNG,SE,CRM,AVGO,ARKK,ABNB,AA,UBER,MA,PTON,MELI,INTC,RIVN,EXPE,V,CMG,RIOT,GME,NKE,AFRM,PLTR,JPM,DWAC,TGT,FCX,UVXY,BNTX,GLD,QCOM,DIA,UAL,MARA,MT,C,SNAP,ISRG,MSTR,SNOW,FXI,ABT,DKNG,CRWD,FDX,LRCX,DOCU,TWTR,COST,GS,JD,TWLO,CAT,XLNX,SOXL,WMT,HOOD,TDOC,SOFI,ALLK,CSCO,XBI,ABBV,LULU,BYND,MDB,TNA,AAL,ASML,PINS,XLE,XLF,BBIO,T,BX,NET,PANW,KMX,DDOG,TLT,ZS,SMH,BB,ORCL,ARQQ,SLV,CVNA,FUTU,HD,BRK.B,PLUG,HLT,BRZU,WYNN,RCL,MRVL,CZR,U,XOM,TTD,ENPH,OKTA,SLB,EWZ,HYG,MOS,BLDR,PG,VIAC,IBM,WFC,AMAT,CVS,ETSY,SAVA,XPEV,USO,TMO,UNH,MGM,NCLH,CHWY,XOP,SAM,MO,DASH,WDC,XLK,MRK,DE,PAYX,DAL,RUN,BITO,ATVI,ASAN,LC,MTTR,LYFT,NOW,APPS,GDX,SPXL,VRTX,DPZ,KWEB,BHC,HTZ,LYV,CVX,ACN,TLRY,ON,BILL,MCD,SEAC,VST,KRE,OXY,GDXJ,CHPT,ADSK,LLY,AGIO,BIDU,QS,TEAM,AXP,CF,GILD,LUV,MDT,FTNT,SQQQ,GE,BIIB,X,IBB,BAX,BZ,RH,MS,M,ALGN,ULTA,MAR,CROX,LOW,FAS,SPOT,PENN,SWKS,OIH,LABU,INTU,VZ,SPCE,WBA,SPLK,EFA,UPRO,DISCK,CLF,UNP,NUE,XLV,CRSP,HON,UPS,LVS,APO,PEP,HUBS,DVN,S,XLY,CAR,DOW,AZO,BBY,FTCH,NEM,BKKT,SBUX,ANET,PBR,MTCH,BMY,TXN,CTAS,OSTK,BILI,PATH,EAT,JNJ,LMND,AUPH,CPNG,BLNK,TTWO,WDAY,FUBO,KO,LMT,EBAY,VOO,URI,SPXU,PDD,MMM,DKS,XRT,VTI,ALLY,SII,ADP,DHR,DISCA,HUT,TZA,NAIL,BRG,WSM,WHR,GOLD,RNG,Z,CMCSA,FANG,REGN,UNG,CLX,QDEL,FSLR,INFY,STX,BBBY,COP,URNM,NTR,SEDG,IEF,ARKG,GPN,JETS,BP,UDOW,CELH,BBIG,EVTL,FSLY,DLTR,TPX,ALB,FCEL,BHP,THO,AVCT,CCJ,HTA,HAL,SCHW,SVXY,GNRC,CNC,JWN,TMUS,AMGN,BLK,GTN,BHVN,XLI,URA,GGPI,MSOS,ATHA,NXPI,JMIA,AI,DT,EFX,JNPR,STNE,EA,SPWR,NKLA,PAGS,CME,EQT,INDI,FVRR,FIVE,SGMS,WISH,MPC,EHC,SU,IWF,CI,SIG,W,KSS,XME,KLAC,ET,VET,LI,LAC,PAYC,AXSM,VALE,NXTD,COUP,ANTM,SI,DIDI,PLBY,MRO,CLOV,TXRH,SM,HES,DFS,PM,VCRA,BMRN,ADI,AMBA,EPD,DXCM,HIMX,ENVX,MSCI,VMW,EW,JBLU,CGC,FISV,FSR,UAN,SPG,MCK,INMD,AR,UAA,NOVA,SWK,IVV,FFIE,CHTR,ALNY,GT,NOK,INSP,COF,VIR,WIX,EOG,GRAB,DG,TOL,RAD,DOCN,SKT,DRI,PNC,IAA,MP,TECL,OPEN,EMB,OTLY,CLDX,CHGG,VLO,PRU,BDX,CFLT,KR,SSO,SLDP,GPS,LAZR,BITF,CWH,TEVA,NUGT,BCRX,HUM,GUSH,PLAY,DHI,ZIM,PROG,LEN,SOXX,RKT,VGT,EDU,IONQ,IGV,VTRS,NEE,BOIL,OCGN,UCO,DOCS,ZEN,COOP,RVMD,YETI,ZI,EXAS,BTBT,ARGX,RTX,SHW,NVTA,FIS,STZ,PL,UNFI,XLU,VRM,OLPX,PTLO,BIGC,MCHP,DB,BTI,OPRX,MDGL,SFIX,CTXS,TAN,SIVB,WEN,MNDY,HPQ,FLGT,RIO,PRPL,APPN,ESTC,KHC,TECK,WKHS,CACC,IYR,YNDX,CRSR,APA,SKLZ,LOVE,KMI,AMRS,ZTS,GFS,URTY,EMN,APD,SAVE,CTSH,BBWI,ASO,ICLR,MDLZ,GRWG,EDIT,SONY,TRIP,ILMN,MX,VEEV,BSX,KBH,DXC,KGC,WM,KEYS,AZN,TSP,TNDM,FTAI,CPE,LTRY,CODX,IRBT,BTCM,EVGO,LSPD,FLT,NVO,TIPT,IWP,LIT,RSX,VFC,CX,APP,SNDL,ZBRA,USB,IEP,HCI,AG,FATE,JBL,DDD,LICY,ACAD,IQ,JNUG,BIRD,LBTYK,ERJ,RDW,LIN,AEM,TER,SMAR,ITB,SDC,EL,RL,PXD,RCAT,IDXX,CPLG,PH,COTY,OLED,ABMD,SNPS,TGLS,SIX,FL,XLP,KLIC,ARNA,TBT,GSK,PHM,TIGR,HEAR,BEKE,TTCF,GTLB,BROS,FDS,PSFE,AEHR,EPAM,GXO,PWR,ARWR,ACM,WOLF,CYBR,ASTS,NTES,NTLA,VOYA,PLD,SYK,SLS,BOOT,FRPT,KLDO,ETN,TECS,ZY,NNDM,TRU,NTNX,GREE,CAKE,FOUR,BALY,AYX,SIMO,CDNS,TJX,AXON,LPI,TENB,CCXI,MPLX,COMM,SPXS,BEAM,SYNA,SBNY,NNOX,MQ,IRNT,ARCT,RKLB,IYT,CMI,OCN,DBX,TASK,AOSL,KIND,CPB,DNA,NVS,GOEV,KOLD,AKUS,XL,CIEN,FLR,BTU,RIDE,CLSK,MTDR,QRVO,UPLD,NVEI,CRNC,EXPD,FIGS,ITCI,STLD,BGFV,AVXL,CNK,SPR,LOGI,GRPN,AGQ,EVBG,XLC,LPX,AVTR,SONO,DAC,SDOW,DBA,SRPT,PLAN,NOC,GIS,THC,MET,PSX,AEO,GLNG,UPWK,GRTX,CSX,RGLD,AOUT,PBF,TGTX,STEM,YINN,IQV,IIVI,HCA,LNG,AER,H,AGCO,DDS,GDRX,IRM,SPGI,NEWR,TSN,JCI,CPRT,SSYS,AVB,BK,STWD,GLW,AIG,ALT,APTV,ZG,ATOM,CENX,GWH,SGH,RDS.A,O,HMHC,IMKTA,FAZ,MBI,LUMN,CYTK,MVIS,ROK,VOD,NDAQ,BNGO,SBAC,IIPR,KKR,ANF,HYLN,VIXY,OPAD,SWAV,SHAK,CLMT,ARKF,STLA,TSCO,TRUP,SWCH,SMFR,XHB,RIG,KBE,GRTS,LNC,OKE,SNCY,LH,BUD,BLOK,EMR,DPST,HCAT,NBIX,CRTX,WPM,ZNGA,INCY,MAC,AVDL,ESSC,CAL,BOX,TPIC,RLX,ABUS,IP,VYM,CWEB,ALK,CAH,EXPR,KRBN,EXC,A,IRTC,OLN,META,HSBC,LITE,SEAH,CEI,PERI,DM,UUP,JKS,CB,LABD,BCTX,MGNI,NLY,FITB,IWD,HIVE,MOMO,WBX,HOG,SRNE,RENT,CCS,FNV,TRV,STM,TFFP,BURL,QSI,GOTU,FORG,ED,NTAP,KRYS,QRTEA,SEV,CLR,SEAS,SENS,SABR,ME,ACLS,DUST,ZBH,TOST,STNG,HIG,DGX,CFVI,GBOX,BXC,NKTR,BIO,TYL,ACB,LWLG,SOXS,CCI,GEF,FAST,ARVL,WEX,TX,OPK,FICO,IYW,CNQ,CAG,AMR,WGO,SQM,CURE,CAN,ERIC,PUBM,VUZI,DUK,SO,OPFI,SOS,AUY,NSC,RRC,RVLV,OSH,RACE,ALDX,DNMR,ROST,RFP,KEY,WST,DECK,TELL,GLBE,MLCO,ICE,AQST,TRIB,ATMR,NRG,SGMO,MDY,SDGR,INDA,LQD,UWMC,LW,GD,DNN,PLL,CBRE,SMG,RPD,DOGZ,PBW,BMBL,CHRW,JXN,OGN,AAWW,YY,LTHM,FPAC,GPI,CRL,VAPO,KD,K,SD,ICL,MKL,NARI,PRTA,ATNM,WY,TUR,ROOT,TREX,AMWD,PAAS,IJR,DELL,VNQ,SRCL,VIPS,HL,CTVA,TTE,CTRA,AMCX,FEZ,TUP,FNKO,QLD,VRSN,HGEN,AKAM,DOMO,OLLI,KMB,XELA,WELL,APPH,BYSI,CHKP,CVE,TAL,TGI,BEEM,HA,CL,CVAC,TWO,AU,GPRO,FUV,PAA,APSG,DVY,IPOF,ARKW,CLNE,PSA,JOBY,PPC,SDS,HZNP,LU,BE,SYF,UUUU,RDFN,XPO,HPE,CTRM,IGT,PEN,SKX,VDE,CSTM,ECL,PPG,EXEL,YUM,MNST,EXR,NEO,PSTG,PGR,TCDA,XPDI,LILM,BG,DD,APLS,SG,ANY,FIVN,HOLX,SBSW,POST,ARDX,AAP,TMC,FHN,GOGL,CYRX,CRON,ALIT,PVH,SAP,CSGP,SYY,ONON,NVTS,PAYA,DLR,STXS,ICLN,APRN,CNI,MTB,ICPT,TXG,SFT,SYRS,EQR,INVZ,CDEV,BLMN,TDC,XAIR,PCT,XSPA,XLB,PZZA,LAD,PTEN,SCCO,VLDR,IONS,GH,MAXR,MMAT,MTH,MSI,SKY,BLI,ENDP,XRX,WMS,OVV,BODY,MUR,RICK,OHI,SKIN,MCHI,CAPR,CTLP,RDS.B,MMP,SBLK,ASTR,YANG,ABR,SWBI,MVST,DISH,ORLY,ERX,GLOB,VUG,DQ,CVM,LYB,TCOM,ONDS,NU,ADS,PD,AHT,MYOV,GBT,AUR,PHUN,VIG,UEC,BGNE,IBN,TFC,TTM,RYAM,CTLT,PAYO,EBIX,KMPH,MGI,CP,NUAN,RSKD,SH,CIBR,EDC,RVNC,MJ,UA,EQIX,PACB,SWN,GFL,AON,FSM,SRE,MGA,FHTX,BITQ,LOTZ,PTRA,INVH,TME,ML,OMF,MRTX,SCHD,BIG,SQSP,R,BLDP,VICI,CNHI,LHX,GDS,ADM,BLDE,DUOL,NMM,CGNT,AREC,PAVM,SILJ,PCG,PAYS,ABCL,UL,POOL,GOGO,SGEN,GMED,ATEC,VT,ASHR,GSL,MNDT,GPRE,XENE,SRTY,CUBE,CMPS,JEF,ATER,NVCR,RPRX,QYLD,HNST,UMC,WB,VTNR,WE,GEVO,EWY,QFIN,ARCB,NVST,TWOU,RGEN,APTS,CBOE,IOVA,PRFT,TM,WOOF,ITW,SLI,CCK,HSY,GRMN,HFC,AJRD,SEER,DOV,HLTH,TECH,INO,LEA,CARR,ARMK,PGEN,LEVI,UBS,XOS,MCO,NXST,TWST,RF,CPRI,FRSH,ONTO,CS,OUST,POSH,BCYC,SPYG,NAUT,IWN,BLL,RGNX,KPLT,CC,LEG,ALL,AMLP,CRVS,AVIR,AMP,CMC,DEO,IOT,AVO,LGND,GOED,RELY,HAE,HBI,ACWI,GATO,TAP,OMC,ODFL,WW,VLTA,CIFR,NCR,MAA,AGCB,ARLP,TVTX,BZH,BMO,AGFY,STT,MKTX,PLNT,CRUS,GSAT,TROW,MATX,RGR,TEN,CKPT,HALO,CAMP,MHK,LOOP,CSIQ,DFEN,KODK,TD,MODV,IMGN,STAA,WAT,PKI,JAZZ,AEVA,UCTT,CR,OIL,COMP,WEBR,OSCR,WU,BKE,VXRT,SEEL,QID,TXT,WMB,CONN,MULN,CG,SCO,CURI,RILY,GNOG,FREY,RGS,INMB,BFLY,DVAX,DAVA,CFG,TRVN,HQY,AMRN,NEGG,GKOS,EQX,VIRT,EIX,BKSY,VSTO,CRIS,PICK,BARK,SAFE,PI,CHK,BXMT,EWW,IBKR,EPI,CDW,LSI,BGS,PII,AGEN,MKC,HBAN,CEIX,RENN,HRL,GAN,TLS,EVRG,D,EDR,ARLO,RKLY,LQDA,BLUE,IS,RRR,MLM,AVLR,HUN,PSTH,AN,BLU,JAMF,PNW,GNW,COO,OCX,SCYX,BWA,ATNF,ATOS,RMBS,ENB,TMV,XM,VERU,PLXP,HP,ENTG,AZEK,SKF,DRIV,HII,SAIL,SOYB,AGNC,SPWH,MPW,NWL,ELY,OLO,HLIT,RSP,PBT,BKR,ARNC,REMX,ATSG,RDWR,IMAB,BJ,TDG,ACI,FMC,SPIR,VAC,MXL,SOLO,ASH,AIR,REKR,RETA,DOMA,AEP,HTHT,EQRX,DMTK,BUG,FXE,XP,PFSI,COPX,LEGN,WFG,CDNA,SSNC,KPTI,COHU,AFL,TRTN,EZU,IT,CND,NOV,INSG,MEDP,BC,HLIO,STAR,ABB,ATUS,KL,ORPH,LAMR,FE,RSG,WLTW,MIDD,IBRX,HZO,RMD,ABC,ASPN,NRZ,NAPA,VNO,BL,SSSS,SITM,PAVE,PLCE,JO,VNOM,XERS,NILE,USD,OMER,TMHC,CDE,BBAI,FOLD,NTP,MKFG,CRK,TSEM,NMRK,WRK,IHI,MED,ZEV,EHTH,SPT,AB,EXPI,WPC,EWJ,BNS,BIP,VWO,TW,YUMC,QCLN,VTWO,GDDY,JNK,TWI,SLAB,IPI,NLS,AIA,AMN,CALX,CM,TBLA,FFIV,TPR,CLOU,GENI,NEP,LSCC,AZTA,ESTE,HYRE,BBD,Y,IMMR,ECH,VTSI,IAC,REE,VSCO,MGY,PFGC,ACHR,IWO,XLRE,IVR,RBOT,FRHC,FRC,PATK,MPWR,MAS,BYD,VBR,UP,CHD,SMSI,TTT,GOOS,ARRY,FNF,CMA,KTOS,BAM,NYMT,ICF,DIN,DRNA,J,VMC,AAOI,FUN,BHG,SFM,SARK,BRX,BRPM,CIM,GO,FIZZ,VGK,AMPL,LEU,AINV,CRTO,TREE,KRNT,ARCC,VTV,MAPS,VCYT,TWM,AHCO,RIGL,COHR,SDIG,AMRX,UNM,TMF,VTR,MGTX,RDN,CUBI,BBW,ALZN,HIPO,REXR,STAG,VBK,SILV,OSUR,VOT,IMCC,ZLAB,TT,POWW,MSM,ESPR,SIL,WH,SAND,AWK,LHDX,SVFA,NYCB,GERN,ASLE,LXRX,WIRE,SINO,CINF,SKYY,CLFD,LLNW,EB,BCPC,COUR,GNUS,MNMD,RRGB,BDSX,CBRL,PLAB,KOPN,FND,NGCA,ACMR,FRT,AVAV,MFA,PETS,NIU,AGI,AMKR,JDST,HIMS,IFF,MTN,HUMA,NEWT,QSR,DHT,PRCH,ATHN,HRB,VB,GMBL,RUTH,CAMT,SAN,PRVB,BAND,DNUT,SAFM,SUNW,SSRM,HBP,PGNY,SJM,MAN,IDEX,PRTY,RMO,JBHT,WDFC,LGF.A,AZUL,VFF,QQQJ,HYZN,FLWS,CHS,CRCT,ATKR,QQQE,TCRR,CARA,MN,COOK,RYAAY,EOLS,CUK,AVYA,DCPH,GLPI,MIME,APT,EGLX,ATCO,AAU,VOOG,LEV,TRGP,MNTS,SIRI,MTSI,ASIX,MESO,DAR,DRIP,VRAY,MANH,MHO,DMRC,PVG,CRDF,SVM,CORN,WWE,NKTX,JLL,IEMG,DVA,CXW,RXRX,DBRG,RWM,REGI,EWG,HLF,ARKQ,LL,MCRB,YELL,TRP,LX,SNV,JYNT,GEO,MTLS,OTIS,CUE,CLVS,WEAT,SEE,STE,ARVN,WING,FOXA,LDI,MUX,ZUO,EDZ,ASRT,DEN,REAL,QQQM,BZUN,ZION,FSK,ROM,LAZ,CSV,ARKO,ELAN,MASI,JOE,AVAN,ASXC,HNP,PPL,SNX,FOCS,FXY,CNDT,SGRY,CPER,TIP,GWW,CBD,AMH,QURE,CCMP,MAIN,ICHR,JAGX,MEXX,ALTO,PRLB,GGAL,EWU,HACK,YCBD,MRAM,DCBO,CPG,MAG,IMAX,WATT,BCS,HST,NE,IDT,VKTX,NAT,OMI,SAIA,EQH,AMX,EGHT,IVW,SPHD,XFOR,NRXP,EH,KOS,DRN,UI,UTHR,SVC,OCUL,IVZ,EUM,ETD,NERV,NTRA,HUBG,DGLY,NFE,LTCH,CZOO,EGO,RXT,AGO,BEN,DLO,NCTY,VNDA,PRQR,NSA,CTIC,CBAT,CHH,EPR,TDY,BTF,SPH,WPRT,KERN,MIR,BKLN,BDRY,CEQP,NICE,AMEH,BFAM,VOX,SHPW,ZIP,PEI,IVAN,PING,DDM,TCS,BNO,TRQ,NLTX,MRNS,MESA,PK,KNDI,VSAT,NM,DRE,SLQT,PRTS,SLG,SPLG,SGFY,PTC,ETRN,DS,RHI,RCUS,ENR,HAS,ARW,VYGR,VWTR,ADCT,BZFD,ARDS,CFRX,ABG,SHLS,CPA,FBHS,MAXN,SSTK,FXC,HTBX,SHY,KT,PCTY,BMTX,ATHX,MRVI,CIO,SAGE,STOR,ARAY,VIXM,HELE,HRI,SCHN,SCI,MORN,MTOR,INVE,CLVR,TCON,UHS,WANT,VEA,RLMD,MKSI,WMC,GFI,TTGT,ASGN,UXIN,HURN,EBON,SUN,MEIP,ZGNX,RNR,FANH,ONTF,MARK,CLVT,PCAR,HIBB,ARCH,CMRE,MSGE,AKBA,DCP,WES,COR,DLHC,MOGO,AQUA,ACIW,BTWN,BRO,JACK,CALT,NGD,GEL,AVRO,AVNW,OMCL,QTNT,TRHC,GES,WCC,BGCP,FROG,CNP,IPO,SB,OYST,TWNK,GPC,MBUU,SHLX,IR,ACGL,DHC,ANSS,SELB,HUYA,BHF,ATO,RYT,NINE,ORGO,SOL,ESGE,ESGR,TGB,SLGC,PIPR,CAE,PACK,EQNR,UMDD,NAK,ISEE,INSE,GRFS,EVAX,IPG,BLKB,EWT,LGIH,PNM,HCC,CTRN,ALPP,SBGI,LXU,RWLK,DSP,OWL,LIDR,MMC,BCLI,ATAI,MGK,ACC,RSI,CPLP,CNRG,APAM,AVPT,LUNA,BKYI,CHDN,EMKR,EPAC,OGI,UPH,ODP,GROW,WTRH,GCO,HWM,WK,DBC,FORM,VIVO,NABL,CNXC,ACET,INFI,PRGO,AMTX,SLCA,IAU,EIGR,ULCC,PSTI,MEOH,RDNT,REI,SRG,IAG,HTGC,UMPQ,EVRI,PCRX,ACRS,HGV,LNTH,GTLS,LDOS,ARBK,XEL,LRN,QGEN,SUPN,ORGN,FRG,BVH,CMRX,ALXO,PTR,XPEL,BHR,STKS,TBBK,FCFS,USAC,FMAC,PIPP,DOLE,VGR,BDSI,IDCC,VWE,PAG,SILK,SKM,SRAD,NUS,VEC,CD,HRTX,FRO,MTZ,LFMD,QTT,CCOI,VMEO,FGEN,YELP,UVV,ITUB,TUEM,MITT,AVNT,BCC,GOCO,PGM,CRS,ILPT,HHC,AES,INFO,PBA,BEST,TMST,MC,NRDS,KBR,FDMT,CXM,WRBY,KDP,IPOD,CMPR,AJG,UWM,SIBN,HMY,EURN,SNA,VCEL,TAK,BGRY,CRC,VVV,SA,DLPN,IRDM,HARP,BBL,LPG,VNRX,TPC,HLI,BPOP,NGG,OSK,SESN,TGH,ATEN,SATS,SKIL,SPLV,DNOW,RVP,AYI,CIVI,AXL,BIOC,LCTX,NLSN,E,SCU,MUSA,NLOK,AQN,AMED,SUI,UROY,TPTX,BETZ,HYFM,KNOP,DXLG,ADMP,GPRK,DOYU,PINC,LOB,AIV,ITOT,OC,CGEN,BLD,AMWL,COCO,BLZE,ATH,CEMI,BZQ,FR,ORI,STKL,CWB,YMM,OEF,EPC,WSC,EXTR,CTXR,CMCT,BR,TFII,EDV,IMO,ATIP,PKG,CVI,GDYN,GSG,SXC,FN,ORMP,MNKD,CE,TROO,RS,CYH,SNBR,TRIT,SELF,VERI,ALRM,GNK,EQOS,UAVS,DOC,RWT,VRNS,CDXS,NOG,JBGS,NNN,AL,DENN,ADPT,HASI,YPF,USX,WAL,AMRC,ZH,DBI,FTGC,ERF,VTIP,VLD,LBRDK,STEP,TK,TPGY,MOH,PBCT,BLRX,AM,BIB,AFG,EVR,SKYT,SLP,ESTA,YOU,PEG,MSGS,IIIN,CSPR,NYT,ALC,PAY,ASND,SPDW,SUM,BERY,COLD,EFC,AGG,MRIN,TEX,PSXP,PIXY,OWLT,BEP,WRAP,MDC,CLW,CANO,KN,TRVG,VREX,DPRO,PHG,ALLO,RFIL,ARE,QTRX,ADNT,CPSH,CPRX,TFX,WIMI,NOVT,VVNT,MPLN,LPTX,INFN,BXP,INGR,JJSF,AUTL,ECPG,EXP,ADT,INBX,TACO,KIM,CNX,HIBL,SPI,AEE,CDZI,ACVA,CARS,ACTG,FTCV,RGA,VRSK,APH,XXII,SNDX,LFC,AME,BJRI,CORT,MCY,EXK,FOA,BENE,PDCE,TSE,PSEC,YALA,HMC,LAND,PKX,URBN,MCB,UIS,OPY,AXDX,QIWI,RDUS,LEAP,MAT,SUNL,SLDB,CTRE,BTG,BAP,CNTY,UBSI,VZIO,SNN,GDEN,KOD,METC,GLOP,FLO,LPSN,FTV,BSQR,ADMA,WLL,FUL,HSIC,EWBC,RNW,WCLD,LYG,REM,ATLC,INN,USFD,CWEN,KTB,OEG,ZROZ,ALGT,LHCG,BPMP,CMS,CPS,ANIP,CCAC,QUBT,EYPT,CIT,GBX,VIEW,LKQ,CMP,IPAR,RC,GGB,AY,IRT,IART,GTE,COLM,ES,IMV,WKEY,OI,SGBX,STIM,RLGY,VXF,LODE,WLK,AKTS,NXE,BRDS,GNCA,PLTK,IBIO,KULR,IMNM,VICR,CQQQ,PBI,OSIS,SHCR,LAUR,IXN,HPP,PMCB,CONE,VC,APLE,AVY,PSQ,SANA,PEGA,FLL,VSH,OTTR,SCOR,XSW,PMT,UYG,ELYS,CLAR,ZNTE,GLL,OBSV,IVE,PDSB,RRX,TNP,GTBP,ALGM,EAST,IHF,OAS,HEPA,ARKX,TALO,CRESY,TITN,THRM,GPMT,ITRI,VNTR,SBH,DX,GL,CRNT,MCMJ,DRIO,AGTC,TGNA,UEPS,MFC,EEV,SBRA,BYRN,ADAP,VG,CALM,MOXC,TRN,CTMX,XSD,AMRK,EWQ,PRPB,UGI,NWSA,INVA,MGPI,TEL,PRI,PXLW,ADVM,SNY,GNL,ESS,GLBS,PRSO,SNII,NEXT,KRP,AVT,APRE,TTEK,HAAC,IWY,IJH,SYNH,WTRG,SACH,GROY,OTRK,ACCD,GOL,NSTG,MTD,TDS,VBIV,EPIX,LUXA,SON,SPYV,TR,EEFT,EYES,UDR,CLSD,TLYS,DV,NOVN,NG,ASTE,ROP,MGP,KRTX,IHRT,GMS,GLPG,WTI,LFG,VRNA,DK,AWAY,TYO,IPA,PODD,WFH,GSIT,VNET,SSD,BRT,MBB,ACHV,SVVC,SLM,GTX,UBX,COWN,KREF,NEPT,CCV,CO,SMPL,BSIG,GRBK,ELMS,PFF,VRTV,DSX,WSR,WEBL,KIRK,LESL,CFX,NMTR,RNLX,TTC,UGL,ESI,NGL,ADTN,OZK,XES,LADR,VAL,RCII,PWFL,BFI,VRS,WEBS,BKH,GCI,CYXT,BSGM,WAB,BOTZ,DXD,CARG,ALEC,EPAY,ROCC,AQB,DTE,ETR,YEXT,PCH,ERY,AQMS,FTI,NTGR,WEC,KBNT,ASX,FCUV,FINX,OUT,SCHG,NBR,ATCX,ILF,DSGX,HOLI,GSM,SCS,LZ,APOG,ORC,LTRX,VV,SCPL,AXTA,VNT,EDUT,IWR,PRTK,PCOR,SLVM,HTOO,VSTM,CVCO,IMBI,SUP,AOS,LIZI,JEPI,JOAN,CVLG,QLYS,ZD,NBEV,SAIC,CERS,DY,ANDE,KARS,GERM,SLNH,CSWC,ORGS,FCG,JJG,BRKR,AGL,PHAS,HVT,L,POWI,BMA,SPRO,BECN,ALBO,KFY,STSA,CCRN,ARI,SDY,SF,JSPR,SUMO,ONEM,RBAC,CSTL,LECO,ATNX,HYMB,SIGA,PPBT,ENLC,EAR,MREO,IGC,SBS,KC,HROW,ALKS,EVER,CLB,CGRN,GNPX,INDL,IIIV,VPG,TMDX,TNK,DIOD,PNR,TEF,AEIS,CCSI,MITK,NAVI,AMZA,SCZ,VRNT,CRBP,GTHX,SPYD,ATHM,TA,BAH,AVEO,HOFV,BKCH,UNIT,FLDM,VIAV,FREQ,BHLB,FSP,MRCY,CRBU,NFG,CSL,FDN,OZON,SPB,GIL,MTW,BTAQ,IEFA,RY,DYAI,DOG,INSW,ABM,BCOR,ATY,SWIM,ABEV,HDB,DRVN,VPU,MBIO,SBEA,DXJ,SHYF,LZB,BTX,MCW,POLY,CVET,VOXX,HYMC,GOOD,IRWD,HESM,BCO,MBT,NNVC,BLND,ESMT,RJF,ZYXI,CLS,INTT,TRMB,LNDC,JOBS,CHNG,JBSS,AVID,LOCO,CRDL,BNED,IMVT,IJS,NX,GMRE,SPHB,MANU,VCR,VO,MTA,SRTS,KNX,NUZE,EMQQ,BRFS,TRYP,MIMO,MNSO,BSM,USIO,EAF,ZIOP,NWE,CPT,SJB,EWH,NSTB,MGIC,DUG,BPT,AYRO,CSLT,PRNT,MTL,ITOS,AXU,HXL,ESRT,NWN,GMDA,HEES,CCB,LAKE,TKR,SREV,PDCO,FWONA,PETZ,CHEF,TXMD,IGM,TTOO,USPH,TU,LNN,RHP,WISA,SRGA,VRRM,IYZ,OMEX,MTCR,AUD,FULC,AMSC,POTX,ZEPP,SCHE,ARCE,ARR,ESNT,FOSL,HBM,GEOS,CABA,EDAP,ICLK,PVL,MYRG,CALA,ZDGE,FIXX,PFLT,TRTX,ITI,NCNO,DTIL,NEOG,XRAY,SLGG,LCI,BRBR,NGM,HT,FXF,RRD,RAPT,USNA,CNR,CRU,CHRS,BEPC,LINC,CELC,AGM,WMG,BATT,QUAL,CLBT,ATRA,FF,YSG,LIVN,GLT,TUYA,BKD,CFR,VISL,FC,EBS,EVFM,EVGN,IDNA,MORF,BIPC,WIT,JKHY,GBIO,MLSS,MTRN,CVGW,DRV,LOPE,GILT,AVDX,BPMC,CWT,BLFS,SBOW,BTAI,XYL,TARO,DFIN,BIZD,TSAT,RDHL,SLVP,EYEN,WD,VHT,DAN,SURF,DNLI,BVS,FREE,CANE,NI,LOV,WRB,AUDC,IBP,BCI,NS,MOV,FPI,EWX,CQP,UMH,TBPH,DTEA,FLEX,CDR,CGNX,HY,CVT,CACI,GP,RELL,EVC,MSB,DGRO,CNM,PIN,WKSP,FBT,ADTX,MRAI,CHX,APG,IGMS,CASY,QTWO,ONCT,ADC,SOI,MMS,HZON,RPM,CEVA,SAH,WRLD,INSM,ULE,MCS,RJI,APDN,RYTM,EWC,CRTD,EOSE,NIB,NMG,HAYW,NUVA,HIBS,UTZ,ALLE,AGS,FTFT,MIDU,GOSS,CERE,FXLV,VGLT,VNE,FLMN,VYGG,AWRE,SLRC,CLPR,RESN,OCUP,GFF,NVMI,CCEP,G,RADA,AMPE,SRC,CNTB,TRUE,PTMN,VRA,LGO,MLKN,FOX,FXN,XPOF,PAR,MTUM,WOR,KURA,ADIL,XPER,DORM,APTO,ZSL,FLUX,ENG,LNT,UONE,ALSN,FNB,NHI,THRY,BCEL,CMTL,SPTN,NVVE,RTLR,IAI,CWCO,CLPT,CRUZ,LPRO,COLB,AVTX,DRD,AMCR,FYBR,GRN,MIC,NEX,SPPI,AMPS,ANGI,LBTYA,SRRK,API,WABC,THCA,WPP,WVE,PTCT,SCSC,PSCE,XBTF,CELU,ZWS,ZUMZ,PHR,JOET,PRIM,EUO,SUPV,SCHB,LRMR,JFIN,KALA,LMNL,BKCC,USL,ENLV,EGP,SID,TALK,SCHM,ATI,FLS,EGLE,WWR,RE,AMG,PEY,NMIH,PILL,FMX,HDV,CRI,CLNN,TNET,LPLA,SUSA,HDSN,PSTX,IGLB,SPEM,DJP,TPB,BCDA,MNTV,FFTY,DCT,ENTA,SJI,MVO,CMCM,PFG,GSHD,PBFX,GIII,NOBL,USAK,YOLO,HUGE,BRMK,RAAS,VBLT,ORTX,FDRV,NNI,BAL,RDY,ZEST,DBO,NJR,RUSL,MFIN,TAC,LTRN,GMTX,TPOR,VERX,SRLP,OPRA,AFMD,GAME,CODI,HALL,TAOP,ARAV,EWA,PDBC,ENOB,SIOX,TUSK,SWIR,PIRS,TRIN,FXA,DUSL,KNBE,KAI,PRPO,RCMT,SKYW,DOOR,DBD,GPK,SWTX,REVG,SCHA,ROG,GWRE,ZTO,GPP,PEB,PLG,CIG,CRMD,MDU,FDIS,FRSX,HNDL,SGLB,OGE,XMTR,PJT,SNP,SIVR,HRMY,PDM,VYNE,EGY,HYD,TDUP,AAIC,PLOW,NEWP,MOO,MDVL,THS,EZA,REYN,GROM,PARR,FBP,ATEX,DMLP,CBT,CHUY,HMLP,OLMA,KBA,ORCC,OII,GDOT,AGR,ARCO,MMYT,ACHC,ZKIN,BASE,LMNR,VERV,SVRA,LII,TROX,AXNX,CDAY,NMRD,PLYA,LSTR,CVEO,PYR,DSL,CRVL,ENZL,KRON,DIG,BF.B,BBH,TFSL,JBT,IGAC,WYY,AFI,ATR,ATAX,XNET,MCG,NATI,AIRG,UAMY,CADE,GLYC,SNCR,UFPI,JJC,VXZ,FST,DAPP,NBTB,ELS,KOP,KXIN,EVA,OCFT,RES,BCE,CLDT,TISI,NXTC,TRX,AYTU,OVID,SMED,RGP,HCM,VVPR,PACW,RXL,IO,CBAY,SGG,FWRD,CATO,MKTW,FNDF,AXGN,APPF,IIN,AEYE,VXUS,USMV,LOMA,POR,OTIC,ROIC,LPL,BDTX,SPTL,IWC,SEAT,SGOL,AXS,IDV,CYD,BLCN,INFL,BITS,PFFA,MLPA,SOHU,VPL,TOKE,AMPY,PCYO,EQC,VEL,ONLN,IZEA,NAVB,BYFC,PDS,CNET,DBB,TMX,EMBK,STC,BW,GLTO,GENE,MMX,RETL,CDLX,YCL,ST,OMP,BWXT,SV,LGF.B,IMTX,KALU,REZ,KDNY,MDWD,NWPX,UBA,DCO,ABIO,WSBC,LMAT,QIPT,KEP,GSBC,CVLT,CLH,EIDO,IMCR,DVOL,RARE,HI,FTEK,AVAH,FTRP,SWI,STON,TNL,PGTI,ENVA,ISUN,CRMT,ASB,FGD,BRY,NRIX,OCSL,KFRC,ENVB,LAZY,REZI,HITI,BCAB,PTF,ETWO,GRAY,LASR,KALV,HBIO,PRPH,AEZS,NVT,RLAY,PEAK,CNNE,DLTH,IVAC,AZPN,LTC,ASPS,SLX,TPH,PRLD,MORT,OSMT,DNB,NCBS,ERII,WOW,ACH,TPVG,FLNT,LIFE,VMD,PPH,RADI,FAF,YMTX,ORN,LCII,CURV,KNSA,KRBP,EWL,LFST,BFOR,GBCI,PYPD,AMPH,GRC,REAX,CWK,BHIL,SCHP,PRGS,ENSG,CHMI,VCTR,CLBS,WSO,GATX,RCI,DRRX,IMMP,TTI,HDRO,XIN,MXI,SJR,COW,GOLF,QLGN,BWEN,FFIC,SMTC,IVC,VECO,URE,AROC,FBRX,JNCE,MYMD,GORO,UFCS,PRAA,AXTI,MYPS,URGN,WTT,PSMT,MRSN,CGAU,NTB,PSB,AERI,CORR,MITC,RLJ,CRGY,APEN,CSR,SUSB,VLRS,NMR,KBWB,SC,ALE,ANIK,RKDA,DADA,RAMP,FTEC,SCWX,PRDO,PB,AEG,SIEN,BBSI,DFH,KRO,FENY,AEL,TWND,RPV,PROF,KSTR,OPTT,TYME,TVTY,IYG,RAIL,KGRN,AGRO,ITA,SMMT,BTNB,BCOV,SLF,GLP,IMUX,ZYME,NOAH,GNLN,KZR,ACRE,STRL,HEXO,SANW,FENC,NESR,MTEM,VCSH,RMAX,ROCK,CDMO,ACR,VEON,REPH,PDP,VAW,NSP,QD,VMI,PTE,ANAB,IEO,PAHC,GLAD,JPUS,IEI,ALV,TTEC,TAST,PASG,MMI,QUAD,ELF,QUOT,KNSL,KAR,IMXI,ALTR,RPAY,AIRC,XLG,SR,ICAD,VITL,SANM,ABEO,IHAK,EWS,INTZ,GALT,INFU,FBIO,VEU,BND,SPYX,SFBS,STAB,HAIN,FDP,FBNC,SWX,HEP,ASMB,DEA,AEMD,AGLE,RYN,RTH,HUBB,EPM,IPAY,EFG,ICVT,SPSC,HLX,IDRA,ADES,GIC,SLNO,MDRX,FRBK,ECOM,HCSG,HERO,IYH,OR,SMFG,SPHQ,VFH,SDIV,WNC,DLX,DSKE,HJEN,THG,EFSC,HEDJ,VTOL,NXGN,VONG,XYLD,BTCY,LQDT,OOTO,SCVL,GVA,VGSH,SIEB,PEJ,OPI,ACIU,APLT,AMYT,ANNX,TCPC,CMBM,AWR,IWS,MINT,CCF,NEXA,EMX,CRHC,EMAN,LE,RMNI,GNTX,PZA,TCMD,MEI,WCN,NVGS,HYLV,MTBC,PST,CASH,SOVO,ENZ,LMACA,PLX,OXM,ARES,RCON,SSL,TTNP,VLY,LTRPA,FPE,KIDS,ROBO,SFE,UFI,BMI,RYI,TV,DAO,SEM,TOWN,EBC,SPLB,FDD,HOOK,CCCS,CDAK,NSIT,TWKS,ESGC,MILE,OOMA,DBVT,VGZ,ONB,INOD,VIA,SQZ,NWG,BELFB,OEC,ANGO,DTN,PXI,COLL,GUNR,CRAI,AWI,IFRA,MNRL,OGS,BATRA,HEI,PAGP,OCDX,TRI,GTIM,TMP,CXDO,FBC,MIRM,PGJ,CBIO,ASHS,NCMI,CSTE,RBBN,MCFE,LOGC,PETQ,SPHY,TDIV,LBRDA,GAIA,ASPU,AADI,IVOL,GSBD,ENS,SCHH,LSXMA,TKC,FORR,BSV,ANIX,FXB,PRAX,ACCO,AAXJ,UGA,SPGP,NEW,BKI,PPTA,EWI,BVN,WWW,SRLN,EGBN,MLI,ING,CPSS,SHOO,OTMO,OBLG,ALTG,CLPS,KFS,RYAN,ATRC,EVOK,FCN,CCCC,EYE,IEX,PSNL,SWM,GHL,XNCR,MSP,LGHL,SMCI,FTK,RLGT,TSLX,ICMB,NPTN,DRH,BGSF,GOAU,LBRT,BWAC,FTXR,MGNX,CAPL,ROL,GLDD,AIMC,MRKR,PTVE,ESPO,FPH,MXCT,IFRX,FXH,KOF,ALVR,KIE,CNCE,PANL,WBT,THCX,REPL,CECE,WHF,CCAP,OPCH,NBSE,CERT,SJW,SFL,NWS,TLIS,NTRS,CAJ,MUDS,CYTO,AX,TCN,SPXC,CRH,SJT,MPAA,DTM,ENV,FCPT,TGS,MMLP,AFIB,MYGN,DHX,NNBR,KYN,CSII,OGIG,DHS,DEM,PXE,VHC,BYTE,UFO,GTY,ORAN,ARC,MWA,ARQT,SRS,DXYN,FWONK,IEZ,FSS,PFMT,MYTE,WOOD,FNGS,NDLS,RYF,CLIR,RWR,FSTR,MANT,PRMW,FLOW,SMIN,ACES,VRT,TMQ,HZN,IDRV,DOOO,KBAL,GBDC,KW,OSS,BMTC,PCVX,MATW,FHI,PSJ,AMTI,KBWD,BMRA,IRIX,TIG,NDSN,ALPN,IPGP,CDTX,BSAC,SRT,AGRX,HRZN,BUR,PNTG,REV,SQFT,OESX,LPCN,EPZM,HAFC,FTS,BDN,PRVA,DDG,DGS,DCI,ELOX,WERN,MOD,FENG,PWP,EFAV,MD,MODN,DEI,CNBS,BOOM,QNST,CCO,TLSA,RWO,TRMK,CTOS,MIXT,GXC,DIV,BXRX,TREB,PBYI,DOX,PYCR,ULBI,MTG,TBF,VNQI,EKSO,RNA,SRVR,VINO,ASYS,FMNB,HMST,MIND,SHC,RM,FHLC,RCKT,CLGN,XHR,FUTY,UONEK,FSTX,KINS,IJJ,RING,DLB,PHX,FARM,VVOS,SLGL,FELE,ROAD,GSKY,LCUT,AP,SFY,DESP,NRP,SASR,IUSG,LVO,EVH,CAC,ONEQ,HONE,SRET,PSN,PBR.A,ETNB,UHT,PGX,VOE,BRAG,FREL,NSSC,ESE,STGW,OCG,IAT,IEA,EPRT,IGOV,FOXF,NHTC,ELP,ASA,TEO,CAAS,AGX,NXRT,KELYA,GCC,AAN,SGC,FULT,MNR,CLXT,NUSI,EWEB,EGAN,AUB,WSFS,BOH,BRSP,SMWB,PSI,IDN,BANF,PDFS,LEGH,SBIO,UNL,AFIN,CLSN,NTUS,APR,MPX,WBS,HFWA,XTN,MTRX,DAIO,RMBL,ACRX,ALTU,SPCX,VIRI,UE,CNA,ELVT,CLLS,ISSC,ENIA,AKRO,ELDN,KSA,GASS,STVN,IHY,MIST,REED,ZEUS,SCHX,GCP,BLV,AIIQ,BQ,SPOK,CTSO,HDGE,USCI,CGBD,VIST,HNGR,FISI,ENFR,UDN,FNLC,PTGX,CNS,CTBI,COMS,ABST,DMAC,VCLT,EPP,JRVR,MUB,NRBO,SHO,CMCO,VIRX,GGG,SPAK,CYCN,NSPR,FDUS,VATE,TRNO,EUFN,REFR,PHO,NYC,PNFP,RYU,LANC,VOLT,ARGT,UMBF,SEF,YMAB,EWD,SPXZ,VRE,TIXT,FKWL,MLPX,GK,ONVO,AFYA,DIVB,ZYNE,REDU,PSP,TS,VTGN,FFBC,ASUR,SCHV,EME,PLSE,CRBN,HE,JG,ACOR,EZPW,YXI,TLMD,MFH,ETON,TURN,PAM,EVLV,BBAR,MUFG,FFNW,SYNL,FORA,EVOP,YRD,SUBZ,PFC,KAMN,AIN,CNYA,PUMP,FAN,SEIC,QUMU,PZN,VYMI,SCM,IMRA,BLX,MCFT,SLYV,SRCE,KMT,JHG,ONTX,STN,FTXO,TCBK,SMRT,HLNE,TG,PEBO,APEI,INT,ASC,EC,EVLO,IBUY,KZIA,TZOO,IBCP,IXC,GDP,ROVR,CW,MRCC,ITT,BLBD,GNE,PBH,BSET,SPAB,OTEX,LFTR,KE,LXP,HR,PAE,FMAT,DLNG,CTT,GAIN,PFSW,PFS,BUZZ,III,WFRD,QRHC,RPTX,MGTA,XPOA,HFFG,LJPC,FTXN,BNDX,BRDG,INNV,SCHL,RUBY,KRMD,HMN,SNEX,IWV,IXJ,TCX,OM,FMTX,CTG,NH,SAFT,CURO,FVE,ENIC,LMFA,DEEP,AMBC,AVNS,INGN,AAON,BRP,VEV,GPL,EQ,IBOC,NWBI,SNLN,HOPE,FDNI,SY,SMHI,FMBI,NGS,VIACA,UEIC,OLP,BNTC,SDEM,AMSWA,AHH,NEON,CNO,FCRD,ADN,REET,HLMN,SCHF,GAZ,CSTR,CHAU,ACER,ONCR,SP,NOMD,SCPH,VS,VDC,SIFY,PXJ,JBI,AVD,PXH,TMFC,SPTM,RCM,HTLD,SND,BSMX,ODT,FOE,EARN,FSTA,KVHI,HTBK,LSXMK,TTSH,DRQ,IMOS,PHAT,PRG,IYE,KMDA,SHEN,SNT,ENTX,STOK,ALKT,BTTX,MACK,OPTN,GNOM,CFB,SGTX,SPEU,GTS,BNL,CDXC,SPSM,WRE,FRBA,SBCF,EFV,CWEN.A,RAVE,HRTG,YVR,XPH,BWX,CMCL,EBF,VCNX,FCF,FNHC,DKL,NTCT,OSW,OCFC,ALTY,NGVC,BANC,CYCC,TOUR,NVNO,MNOV,NFBK,FHB,PCTI,CRWS,RYB,RMTI,NBRV,YQ,XOMA,FSMD,ALHC,CHIX,SRAX,XSOE,SOCL,RGLS,ZETA,RVSB,FTDR,PNNT,ITP,FM,VRCA,IGIB,SYPR,MERC,SPMD,CUZ,BIOX,ORIC,QMCO,CDK,GREK,NYMX,BREZ,ATRS,RCD,RNWK,CPUH,GLMD,ERYP,IGE,AKR,CSBR,SGU,BJK,VGIT,OXSQ,MCBC,AUS,NMTC,ETAC,PRA,BCBP,TTMI,STCN,GNSS,BBVA,SECO,FNCL,GYLD,XHS,KRNY,UVE,NL,CNSL,CYB,APTX,QUIK,TMCI,SDVY,FBRT,WETF,ANTE,UGP,PBPB,AUTO,OSG,SMP,BKEP,ACA,XBIO,ATXS,EGRX,IMH,RVPH,DON,UTSI,TGP,HAUZ,ASLN,EXTN,LTPZ,BSBR,DES,NERD,CASA,AWH,VWOB,IEV,PIO,IGHG,USRT,TPYP,SMMD,HAIL,KRG,CBZ,CHE,EEX,LRGF,EZM,IYJ,SNSR,DFE,EWV,UBR,DSTL,JPIN,TIMB,EWN,SPNT,HEWJ,ASEA,BBU,CPSI,GVIP,GIGB,GSEW,PKB,PBP,PBD,PUI,JHML,XTL,WTS,NANR,CFA,LVOX,ZVO,MRC,THTX,RWK,FBK,NRT,AUMN,FYX,JPST,NRDY,PCY,SBUG,ALLT,IFGL,SYBX,SMOG,FQAL,TRST,SHYG,ATGE,FTHM,HYS,HSKA,WAFD,GINN,CNXT,BIV,FXD,LXFR,KMPR,KTCC,RUSHA,SYLD,SOXQ,EELV,PHB,KWR,DBTX,OMAB,JP,LGLV,NSR,VIS,CPIX,ECNS,IXG,GAU,SPFF,GTEK,UCBI,JW.A,FEM,EEMV,HOMZ,DZSI,KVSA,BBCA,DBEF,NFRA,SPSB,NOA,MASS,KCCA,RDVT,NXTG,FDVV,LBAI,IJK,IYF,BTN,IDYA,RWJ,FXL,ELA,COMT,VNLA,IETC,LFVN,OVLH,ACEL,DGICA,PKW,ZNH,STIP,DBEU,BV,GURU,SCHJ,VTEB,JMST,TREC,PTNQ,TCBI,NGVT,GSY,CNMD,PPA,TILE,LOAN,EVTC,FTCS,ATMP,KROS,PSCM,RTM,GIFI,PRFZ,HYXU,VPN,NAN,CAPE,HIW,DBV,PULS,COWZ,FTRI,EPS,SPTS,MBWM,NLR,SCHC,BCSF,EFAS,RJZ,MGLN,CULP,JJA,CSSE,RJN,PAWZ,SPNE,FIBK,USFR,QCRH,XHE,MAGA,PSO,SXI,WWD,WPS,SPTI,JJT,AIEQ,BFTR,FCOM,AQGX,FLBR,USIG,EAGG,TOTL,IFN,CTS,GSS,CYBE,DXPE,ERTH,ASRV,BBC,IZRL,JJS,GDOC,LCTU,CLDL,USHY,PXF,AFK,XNTK,KXI,RWX,FLOT,PSCT,DVYE,FAB,TYD,JUST,DFAC,DFAI,SGDM,OFS,VSS,FDRR,CGW,SUNS,CBSH,CNOB,STPZ,IRBO,MOON,GSLC,DFUS,ITRN,PRN,CCNE,AMOT,PRK,SLY,CXSE,SLGN,PRF,KEMQ,JPEM,SRDX,BOAT,HTEC,GENC,GLRE,SPIP,FLQL,GSIE,FDLO,IBBQ,KOMP,BBIN,VFVA,KORU,FIDI,SCHY,HAP,FNK,ICFI,FNX,XSVM,GVI,FCBC,PLRX,WLMS,PEO,BAB,RCEL,SECT,AJX,FLCH,CIVB,COGT,EXLS,PKOH,LDEM,PSEP,SHE,MUNI,BTTR,DBE,NTZO,ONCS,RODM,AMJ,PGRE,EDOC,GHM,PSL,FXG,PSCC,CRPT,AIZ,DRTT,RGI,UBT,RJA,WLDN,GLCN,RPG,RDI,URTH,FIX,HTBI,HCCI,LEMB,HSC,HSII,EURL,HWKN,XT,DGII,ROLL,KRMA,FIXD,TFLO,FALN,HEFA,FIDU,WLKP,IUSB,FLIC,ROBT,FNDB,FRGI,IHDG,IDLV,DFAT,GII,ECOL,RPAR,HYBB,BIL,BHE,MHLD,XMVM,CEMB,FTSM,GHYB,CNXN,PLUS,PLXS,FXO,SHV,PRSR,LFT,XAR,IEUR,CLBK,ADUS,ATNI,ATRO,OSPN,MGRC,CENT,FARO,NVEE,BSRR,GIB,GRUB,HYZD,INCO,XENT,VBTX,DWX,ISTB,LILA,FNDE,BATRK,GWRS,XSLV,LMB,GTYH,PCSB,FDMO,DFAU,KEX,RYE,TH,FIW,SCHK,GMAB,XGN,IQLT,CALF,EBND,PMVP,SCHR,VRDN,LQDI,DSEY,SNPO,ECVT,DH,GBIL,WHG,CLDS,VTWG,AIQ,PIE,RZV,QQEW,FEX,SMBC,LBJ,EEMA,IXUS,RBCAA,LVHD,GOVT,IGF,EBIZ,IJT,WNEB,AIRR,FYT,PEZ,ESGU,FSV,MDIV,DAX,IGSB,PIZ,USMC,OFIX,PFFD,BBAX,FIVG,FVAL,IDEV,DFAS,OUSA,KBWY,TAIL,IAGG,TFI,SSP,PAX,FXR,GRID,SHBI,BFIT,WTFC,LAW,IVT,KLR,LILAK,VIGI,CWI,ZIXI,RLI,UIHC,ZNTL,VMBS,VIV,CUTR,LUNG,SPIB,KYMR,SFNC,MGC,SNDR,IDA,EMLC,OIS,FTXH,CHIQ,AMBP,EMLP,BRF,HNI,HOFT,PJP,HTLF,REG,IWX,FRME,THD,FXZ,BBDC,DLN,DEF,FFIN,FPX,FVD,INDY,FDL,GABC,MFG,IWL,INDB,CIGI,PBS,IOO,NHC,AMSF,NMFC,GNR,MDYG,EXPO,PCEF,MGEE,EUSA,AIT,PPBI,PFBC,SSB,PGC,STFC,BFIN,STRA,MOAT,SPNS,AMNB,AROW,CSGS,BANR,CZNC,MDYV,SMBK,ABCB,AZZ,AAT,THFF,YCS,MSEX,AVUV,HAYN,EVX,IQDF,RXDX,PSCF,JJE,DAKT,GBUG,BOND,GWB,BMED,B,EQWL,FTA,SINV,KBUY,IGRO,BSEA,FPXI,SDOG,KFVG,ZHDG,AVA,MLR,USDU,APYX,VVI,REK,MYY,DGL,GLIN,NBHC,UST,FTXD,LIQT,ORLA,HEZU,CRNX,LEGR,PRO,QQH,HBB,PTLC,GMET,WCBR,CGA,EPV,PNQI,GMF,HLLY,MFGP,GTES,USM,CIXX,IPKW,IHE,IDU,LD,KLNE,BDC,BRC,XMHQ,HTH,SRI,EFZ,FXP,TBI,SUSL,CBU,RWL,CVGI,LUB,IWB,AZRE,ACEV,NR,ISBC,CARE,IBTX,LYTS,FINV,ICUI,MMSI,MSA,MEG,USAP,KNTE,ANPC,CHCO,TIPX,CIA,QEFA,ADV,MOSY,OFC,USDP,DCOM,LKFN,IYY,RFL,MTX,VTEX,HWC,SLYG,IOSP,ELD,EES,IFV,PFM,STBA,FTXL,CVBF,CMF,NOTV,TPST,GOEX,UNVR,PHIO,REW,IQDG,HDEF,SNPE,BUYZ,BBCP,DTEC,EPHY,CHT,GB,EWUS,FXU,SGDJ,DNL,DWM,EWK,NEU,GWX,CVCY,REGL,PBJ,CTEC,ORA,PUK,HOMB,RBA,JJN,NPO,FBND,MNRO,NETL,MOG.A,DYN,SCL,PTBD,STL,SIGI,BSN,SXT,INVO,ASR,MRTN,FV,CIB,CPF,CRD.A,CPK,BKF,FOR,PKE,AVDV,FNGG,DJD,LQDH,QTEC,TMAT,CMLT,QTUM,EMGF,VQS,PWSC,IVLU,DGRW,OUNZ,HIL,SPDN,CHRA,NTCO,STTK,SPGM,CONX,HYLB,UTSL,MJXL,ICSH,DFAX,HBNC,OFG,KB,VONV,IGN,RNST,DLS,MGV,BRKL,SCHZ,SBSI,AGYS,CRY,CFFN,FNDA,IMTM,XBIT,WTTR,FRTA,EMXC,PLMR,CGEM,KRC,SCHO,TBK,ESGD,ASAI,ALFA,QDF,FNY,VEDL,KSU,FCA,BBJP,VLUE,NEAR,SPMB,VOOV,FEP,FLRN,RPT,FTC,IUSV,TRS,FNDX,STRO,AXLA,VER,OLK,VCIT,FMS,BTCR,YPS,AQWA,BBEU,LOUP,SVFAU,ELMD,DTOX,JJP,BTEK,XBUY,BBP,ASPY,JJU,JJM,MVP,AWYX,SILX,DSPC,KRA,UVSP,WNS,UHAL,UTI,HSTM,HMTV,GSP,ITGR,TDW,THR,TACT,TRC,TWIN,NTWK,BCM,MNTX,MG,MCHX,MCRI,PCOM,PTH,PCYG,PESI,PSCH,CENTA,CIR,LIND,CROC,CWST,BNFT,LEJU,TSQ,NVRO,AGFS,SITE,MRUS,JELD,CAAP,TUFN,TARA,FUSN,MAX,BSY,TSHA,LNSR,ALGS,SBTX,BTRS,NUVB,HCIC,LYEL,XPRO,CWAN,LCNB,MYE,MRLN,CMBS,ANAT,KURE,RDIV,XITK,DBP,YYY,PWV,EWRE,TTAC,GXTG,VLU,AFTY,DBJP,KCE,WDIV,GAMR,IWFH,HYGH,CAF,ECON,EWGS,GEM,ONEY,HEEM,LOWC,QUS,XWEB,DIVO,XMMO,ECLN,EINC,FCPI,GOVZ,AVUS,OVT,EBLU,DOZR,UTL,WASH,WSBF,SJNK,XPP,SITC,HYLD,DBS,RFV,IYC,FRI,CCLP,TNC,TLH,ESCA,EIG,EET,EZJ,EWM,MZZ,BIS,PYZ,PID,PFI,PBE,PSCD,SBM,DGRS,SMN,CEW,LMRK,CHAD,PUTW,MILN,EMTY,CHIC,YORW,QQXT,QABA,KBWR,XMLV,OSBC,WTBA,UNF,WMK,VEGI,VOC,UXI,UYM,LFUS,HCKT,HEI.A,VSEC,DFJ,RYH,FBIZ,DSI,DRW,DWAS,DXJS,FBMS,DVD,FBZ,FTSL,FYC,IAK,GXG,IMLP,ITM,ISRA,IXP,IYM,IYK,TBNK,EDIV,NP,EEMS,ERIE,EXI,EWP,BKU,BF.A,BOKF,BUSE,PDN,FTAG,PGF,SAA,PSCI,PWB,SCJ,SIZE,ACWV,ACWX,ALEX,AGZ,ALG,CARZ,CASS,CATY,FNDC,CSD,CVY,CUT,SLQD,VRP,EQAL,RDVY,HEWG,TOLZ,LMBS,CRAK,SMDV,INTF,CATH,ITEQ,SPVU,ABTX,FTXG,GENY,WHD,FNCB,VTC,CHIK,IGIC,GCMG,ANGL';

  var config = {
    method: 'get',
    url: 'https://ql.stocktwits.com/batch?symbols=AAL%2CAAPL%2CACB%2CADA.X%2CALDX%2CAMC%2CAMD%2CAMZN%2CAQST%2CATOS%2CBA%2CBABA%2CBAC%2CBB%2CBE%2CBFRI%2CBNGO%2CBRG%2CBTC.X%2CBYND%2CCCL%2CCEI%2CCGC%2CCLOV%2CCOIN%2CCRON%2CCTRM%2CDAL%2CDGNS%2CDIA%2CDIS%2CDJIA%2CDKNG%2CDOGE.X%2CENPH%2CETH.X%2CF%2CFB%2CFCEL%2CFSR%2CGE%2CGEVO%2CGILD%2CGME%2CGNUS%2CGOOG%2CGOOGL%2CGPRO%2CHCMC%2CHEX.X%2CHNST%2CIBIO%2CIDEX%2CINO%2CINTC%2CJAGX%2CJNUG%2CJPM%2CLCID%2CLQDT%2CLTC.X%2CLTRY%2CLUNA.X%2CMARA%2CMRNA%2CMSFT%2CMU%2CMVIS%2CNAKD%2CNFLX%2CNIO%2CNKE%2CNKLA%2CNKTR%2CNNDM%2CNOK%2CNVAX%2CNVDA%2COCGN%2CPFE%2CPLBY%2CPLTR%2CPLUG%2CPRPL%2CPYPL%2CQQQ%2CRBA%2CRIOT%2CRKT%2CROKU%2CSAVA%2CSBUX%2CSHIB.X%2CSHOP%2CSNAP%2CSNDL%2CSOPA%2CSOS%2CSPCE%2CSPX%2CSPY%2CSQ%2CSRNE%2CT%2CTLRY%2CTOPS%2CTSLA%2CTWTR%2CUBER%2CUVXY%2CV%2CVISL%2CVSAT%2CVXRT%2CWISH%2CWKHS%2CWMT%2CXOM%2CXRP.X%2CXSPA%2CYFI.X%2CZOM',
    headers: {
      'authority': 'ql.stocktwits.com',
      'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"',
      'sec-ch-ua-mobile': '?0',
      'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36',
      'sec-ch-ua-platform': '"macOS"',
      'accept': '*/*',
      'origin': 'https://stocktwits.com',
      'sec-fetch-site': 'same-site',
      'sec-fetch-mode': 'cors',
      'sec-fetch-dest': 'empty',
      'referer': 'https://stocktwits.com/',
      'accept-language': 'en-US,en;q=0.9'
    }
  };

  axios(config)
      .then(function (response) {
        //console.log(JSON.stringify(response.data));
        res.send(response.data)
      })
      .catch(function (error) {
        //console.log(error);
        res.send(error)
      });
})


let allStockInfo = []

app.get('/getCallPutRatio', (req,res) =>{
  res.send(allStockInfo)
})


function startProcess() {

  setInterval(function(){
    var data = 'draw=3&columns%5B0%5D%5Bdata%5D=Symbol&columns%5B0%5D%5Bname%5D=Symbol&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=CompanyName&columns%5B1%5D%5Bname%5D=CompanyName&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=CurrentPrice&columns%5B2%5D%5Bname%5D=CurrentPrice&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=PricePctChg&columns%5B3%5D%5Bname%5D=PricePctChg&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=TradeCount&columns%5B4%5D%5Bname%5D=TradeCount&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=TotalVolume&columns%5B5%5D%5Bname%5D=TotalVolume&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=true&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=AvgVolume_90Day&columns%5B6%5D%5Bname%5D=AvgVolume_90Day&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=true&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B7%5D%5Bdata%5D=RelativeVolume&columns%5B7%5D%5Bname%5D=RelativeVolume&columns%5B7%5D%5Bsearchable%5D=true&columns%5B7%5D%5Borderable%5D=true&columns%5B7%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B7%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B8%5D%5Bdata%5D=CallVolume&columns%5B8%5D%5Bname%5D=CallVolume&columns%5B8%5D%5Bsearchable%5D=true&columns%5B8%5D%5Borderable%5D=true&columns%5B8%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B8%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B9%5D%5Bdata%5D=PutVolume&columns%5B9%5D%5Bname%5D=PutVolume&columns%5B9%5D%5Bsearchable%5D=true&columns%5B9%5D%5Borderable%5D=true&columns%5B9%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B9%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B10%5D%5Bdata%5D=PutPercentage&columns%5B10%5D%5Bname%5D=PutPercentage&columns%5B10%5D%5Bsearchable%5D=true&columns%5B10%5D%5Borderable%5D=true&columns%5B10%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B10%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B11%5D%5Bdata%5D=TotalNotional&columns%5B11%5D%5Bname%5D=TotalNotional&columns%5B11%5D%5Bsearchable%5D=true&columns%5B11%5D%5Borderable%5D=true&columns%5B11%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B11%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B12%5D%5Bdata%5D=AvgNotional_90Day&columns%5B12%5D%5Bname%5D=AvgNotional_90Day&columns%5B12%5D%5Bsearchable%5D=true&columns%5B12%5D%5Borderable%5D=true&columns%5B12%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B12%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B13%5D%5Bdata%5D=RelativeNotional&columns%5B13%5D%5Bname%5D=RelativeNotional&columns%5B13%5D%5Bsearchable%5D=true&columns%5B13%5D%5Borderable%5D=true&columns%5B13%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B13%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B14%5D%5Bdata%5D=CallNotional&columns%5B14%5D%5Bname%5D=CallNotional&columns%5B14%5D%5Bsearchable%5D=true&columns%5B14%5D%5Borderable%5D=true&columns%5B14%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B14%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B15%5D%5Bdata%5D=PutNotional&columns%5B15%5D%5Bname%5D=PutNotional&columns%5B15%5D%5Bsearchable%5D=true&columns%5B15%5D%5Borderable%5D=true&columns%5B15%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B15%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=11&order%5B0%5D%5Bdir%5D=desc&start=0&length=6000&search%5Bvalue%5D=&search%5Bregex%5D=false';

    var config = {
      method: 'post',
      url: 'https://marketchameleon.com/Reports/ovrMainData',
      headers: {
        'authority': 'marketchameleon.com',
        'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36',
        'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
        'x-mobdisp': 'true',
        'accept': 'application/json, text/javascript, */*; q=0.01',
        'sec-ch-ua-platform': '"macOS"',
        'origin': 'https://marketchameleon.com',
        'sec-fetch-site': 'same-origin',
        'sec-fetch-mode': 'cors',
        'sec-fetch-dest': 'empty',
        'accept-language': 'en-US,en;q=0.9',
        'Cookie': 'ASP.NET_SessionId=ydkp2ggmhyavrwfvtg2n1ic3; v1=46050630; ak_bmsc=4C3D9834FE06F908FE9F916D0A4CD6F7~000000000000000000000000000000~YAAQT2bNFzryGL19AQAAiKG95Q6ri4XI/HE0ynl6yHNinJLNPapSLDcqarIR2OFH2r77zr2HwAGp25o5pVj8sVvT/Jh2ewotau3GFsGTeAo3u8C62axSbOBMmmGOT1G3zEkYCf66R6Q07iy0NLwf6oFhkjc86GgoB9VT+svKZkWHtFcd1/o7y9M1wtZ66qgK336Jq/n7A3NiuybLmLxzwe5xkYZb0PVbaJgrE7hXgomoZouy/B2K2r3kPCca/8KXzOEgSJ0uvJTySo/oWMvnBBOTf8NrunFs4RtwqJa/+633CSNS2lOyfhF4onmg5A8D7ZwbEF8rbrKvr7I0vo/PK+53WWRWOonhKDvJniKGmf9/f+TSSM5hcC7rqdFMVGScAPmI; bm_sv=767AC12BB7AE8C58A0CF7E1C848E6E67~DymIBayHhBT+nB9HjCRspwurbAYrpaQsAQ/F+2yZiZ89wKi8fY5y9kbrIDNFre2HI6LEFH2NyACqEzyJ8pmaKBHKCP9Ee5c+cOnKO5pFI2bLKn2NqbTg1t4gXl6Q2TXsLzbVI2i+QglCEPz5KVvBIjyQTCjMtCTnTTTvz4fvoaY='
      },
      data : data
    };

    axios(config)
        .then(function (response) {
          const parsedData = _.map(response.data.data, e=> {
            e.SymbolLinkHtml = null;
            return e})
          allStockInfo = parsedData;
          // //console.log(JSON.stringify(parsedData))
        })
        .catch(function (error) {
          //console.log(error);
        });
  }, 10000);


}




app.listen(port, () => {
 //startProcess();
})

// const temp = {
//   "time": "Time",
//   "symbol": "Symbol",
//   "name": "Company Name",
//   "eps": "EPS",
//   "surprise": "% Surprise",
//   "marketCap": "Market Cap",
//   "fiscalQuarterEnding": "Fiscal Quarter Ending",
//   "epsForecast": "Consensus EPS* Forecast",
//   "noOfEsts": "# of Ests"
// }
//
// const columns = _.map(temp, (a, b)=> {return {'Header': a, 'accessor' :b}})
//
//
//
//
//
// //console.log(JSON.stringify(derivedColumns))



